### ISSUE TITLE
Online okurken sonraki başlık önceki başlık

### ISSUE THREAD

**Issue by fg** [sdogruyol/crystal_for_rubyists#2]
Selam online okurken sonraki başlık, önceki başlık linkleri ekleyelim mi? Her seferinde listeye geri dönmek yerine güzel olur bence, ne dersin?

**Comment by sdogruyol** [comment]
Selam @fg, öneri için teşekkürler fakat kitap / site tek kaynak koddan üretildiği için bunun yerine tek parça olan versiyonu okumak daha kullanışlı olacaktır.
